# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_Factor')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_Factor')
    _Factor = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_Factor', [dirname(__file__)])
        except ImportError:
            import _Factor
            return _Factor
        if fp is not None:
            try:
                _mod = imp.load_module('_Factor', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _Factor = swig_import_helper()
    del swig_import_helper
else:
    import _Factor
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _Factor.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _Factor.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _Factor.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _Factor.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _Factor.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _Factor.SwigPyIterator_equal(self, x)

    def copy(self):
        return _Factor.SwigPyIterator_copy(self)

    def next(self):
        return _Factor.SwigPyIterator_next(self)

    def __next__(self):
        return _Factor.SwigPyIterator___next__(self)

    def previous(self):
        return _Factor.SwigPyIterator_previous(self)

    def advance(self, n):
        return _Factor.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _Factor.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _Factor.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _Factor.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _Factor.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _Factor.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _Factor.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _Factor.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class intArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, intArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, intArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _Factor.new_intArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Factor.delete_intArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _Factor.intArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _Factor.intArray___setitem__(self, index, value)

    def cast(self):
        return _Factor.intArray_cast(self)
    if _newclass:
        frompointer = staticmethod(_Factor.intArray_frompointer)
    else:
        frompointer = _Factor.intArray_frompointer
intArray_swigregister = _Factor.intArray_swigregister
intArray_swigregister(intArray)

def intArray_frompointer(t):
    return _Factor.intArray_frompointer(t)
intArray_frompointer = _Factor.intArray_frompointer

class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _Factor.new_doubleArray(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Factor.delete_doubleArray
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _Factor.doubleArray___getitem__(self, index)

    def __setitem__(self, index, value):
        return _Factor.doubleArray___setitem__(self, index, value)

    def cast(self):
        return _Factor.doubleArray_cast(self)
    if _newclass:
        frompointer = staticmethod(_Factor.doubleArray_frompointer)
    else:
        frompointer = _Factor.doubleArray_frompointer
doubleArray_swigregister = _Factor.doubleArray_swigregister
doubleArray_swigregister(doubleArray)

def doubleArray_frompointer(t):
    return _Factor.doubleArray_frompointer(t)
doubleArray_frompointer = _Factor.doubleArray_frompointer

class VecInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _Factor.VecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Factor.VecInt___nonzero__(self)

    def __bool__(self):
        return _Factor.VecInt___bool__(self)

    def __len__(self):
        return _Factor.VecInt___len__(self)

    def __getslice__(self, i, j):
        return _Factor.VecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Factor.VecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Factor.VecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Factor.VecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Factor.VecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Factor.VecInt___setitem__(self, *args)

    def pop(self):
        return _Factor.VecInt_pop(self)

    def append(self, x):
        return _Factor.VecInt_append(self, x)

    def empty(self):
        return _Factor.VecInt_empty(self)

    def size(self):
        return _Factor.VecInt_size(self)

    def swap(self, v):
        return _Factor.VecInt_swap(self, v)

    def begin(self):
        return _Factor.VecInt_begin(self)

    def end(self):
        return _Factor.VecInt_end(self)

    def rbegin(self):
        return _Factor.VecInt_rbegin(self)

    def rend(self):
        return _Factor.VecInt_rend(self)

    def clear(self):
        return _Factor.VecInt_clear(self)

    def get_allocator(self):
        return _Factor.VecInt_get_allocator(self)

    def pop_back(self):
        return _Factor.VecInt_pop_back(self)

    def erase(self, *args):
        return _Factor.VecInt_erase(self, *args)

    def __init__(self, *args):
        this = _Factor.new_VecInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _Factor.VecInt_push_back(self, x)

    def front(self):
        return _Factor.VecInt_front(self)

    def back(self):
        return _Factor.VecInt_back(self)

    def assign(self, n, x):
        return _Factor.VecInt_assign(self, n, x)

    def resize(self, *args):
        return _Factor.VecInt_resize(self, *args)

    def insert(self, *args):
        return _Factor.VecInt_insert(self, *args)

    def reserve(self, n):
        return _Factor.VecInt_reserve(self, n)

    def capacity(self):
        return _Factor.VecInt_capacity(self)
    __swig_destroy__ = _Factor.delete_VecInt
    __del__ = lambda self: None
VecInt_swigregister = _Factor.VecInt_swigregister
VecInt_swigregister(VecInt)

class VecVecInt(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecInt, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecInt, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _Factor.VecVecInt_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Factor.VecVecInt___nonzero__(self)

    def __bool__(self):
        return _Factor.VecVecInt___bool__(self)

    def __len__(self):
        return _Factor.VecVecInt___len__(self)

    def __getslice__(self, i, j):
        return _Factor.VecVecInt___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Factor.VecVecInt___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Factor.VecVecInt___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Factor.VecVecInt___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Factor.VecVecInt___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Factor.VecVecInt___setitem__(self, *args)

    def pop(self):
        return _Factor.VecVecInt_pop(self)

    def append(self, x):
        return _Factor.VecVecInt_append(self, x)

    def empty(self):
        return _Factor.VecVecInt_empty(self)

    def size(self):
        return _Factor.VecVecInt_size(self)

    def swap(self, v):
        return _Factor.VecVecInt_swap(self, v)

    def begin(self):
        return _Factor.VecVecInt_begin(self)

    def end(self):
        return _Factor.VecVecInt_end(self)

    def rbegin(self):
        return _Factor.VecVecInt_rbegin(self)

    def rend(self):
        return _Factor.VecVecInt_rend(self)

    def clear(self):
        return _Factor.VecVecInt_clear(self)

    def get_allocator(self):
        return _Factor.VecVecInt_get_allocator(self)

    def pop_back(self):
        return _Factor.VecVecInt_pop_back(self)

    def erase(self, *args):
        return _Factor.VecVecInt_erase(self, *args)

    def __init__(self, *args):
        this = _Factor.new_VecVecInt(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _Factor.VecVecInt_push_back(self, x)

    def front(self):
        return _Factor.VecVecInt_front(self)

    def back(self):
        return _Factor.VecVecInt_back(self)

    def assign(self, n, x):
        return _Factor.VecVecInt_assign(self, n, x)

    def resize(self, *args):
        return _Factor.VecVecInt_resize(self, *args)

    def insert(self, *args):
        return _Factor.VecVecInt_insert(self, *args)

    def reserve(self, n):
        return _Factor.VecVecInt_reserve(self, n)

    def capacity(self):
        return _Factor.VecVecInt_capacity(self)
    __swig_destroy__ = _Factor.delete_VecVecInt
    __del__ = lambda self: None
VecVecInt_swigregister = _Factor.VecVecInt_swigregister
VecVecInt_swigregister(VecVecInt)

class VecDouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecDouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecDouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _Factor.VecDouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Factor.VecDouble___nonzero__(self)

    def __bool__(self):
        return _Factor.VecDouble___bool__(self)

    def __len__(self):
        return _Factor.VecDouble___len__(self)

    def __getslice__(self, i, j):
        return _Factor.VecDouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Factor.VecDouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Factor.VecDouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Factor.VecDouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Factor.VecDouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Factor.VecDouble___setitem__(self, *args)

    def pop(self):
        return _Factor.VecDouble_pop(self)

    def append(self, x):
        return _Factor.VecDouble_append(self, x)

    def empty(self):
        return _Factor.VecDouble_empty(self)

    def size(self):
        return _Factor.VecDouble_size(self)

    def swap(self, v):
        return _Factor.VecDouble_swap(self, v)

    def begin(self):
        return _Factor.VecDouble_begin(self)

    def end(self):
        return _Factor.VecDouble_end(self)

    def rbegin(self):
        return _Factor.VecDouble_rbegin(self)

    def rend(self):
        return _Factor.VecDouble_rend(self)

    def clear(self):
        return _Factor.VecDouble_clear(self)

    def get_allocator(self):
        return _Factor.VecDouble_get_allocator(self)

    def pop_back(self):
        return _Factor.VecDouble_pop_back(self)

    def erase(self, *args):
        return _Factor.VecDouble_erase(self, *args)

    def __init__(self, *args):
        this = _Factor.new_VecDouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _Factor.VecDouble_push_back(self, x)

    def front(self):
        return _Factor.VecDouble_front(self)

    def back(self):
        return _Factor.VecDouble_back(self)

    def assign(self, n, x):
        return _Factor.VecDouble_assign(self, n, x)

    def resize(self, *args):
        return _Factor.VecDouble_resize(self, *args)

    def insert(self, *args):
        return _Factor.VecDouble_insert(self, *args)

    def reserve(self, n):
        return _Factor.VecDouble_reserve(self, n)

    def capacity(self):
        return _Factor.VecDouble_capacity(self)
    __swig_destroy__ = _Factor.delete_VecDouble
    __del__ = lambda self: None
VecDouble_swigregister = _Factor.VecDouble_swigregister
VecDouble_swigregister(VecDouble)

class VecVecdouble(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VecVecdouble, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VecVecdouble, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _Factor.VecVecdouble_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _Factor.VecVecdouble___nonzero__(self)

    def __bool__(self):
        return _Factor.VecVecdouble___bool__(self)

    def __len__(self):
        return _Factor.VecVecdouble___len__(self)

    def __getslice__(self, i, j):
        return _Factor.VecVecdouble___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _Factor.VecVecdouble___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _Factor.VecVecdouble___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _Factor.VecVecdouble___delitem__(self, *args)

    def __getitem__(self, *args):
        return _Factor.VecVecdouble___getitem__(self, *args)

    def __setitem__(self, *args):
        return _Factor.VecVecdouble___setitem__(self, *args)

    def pop(self):
        return _Factor.VecVecdouble_pop(self)

    def append(self, x):
        return _Factor.VecVecdouble_append(self, x)

    def empty(self):
        return _Factor.VecVecdouble_empty(self)

    def size(self):
        return _Factor.VecVecdouble_size(self)

    def swap(self, v):
        return _Factor.VecVecdouble_swap(self, v)

    def begin(self):
        return _Factor.VecVecdouble_begin(self)

    def end(self):
        return _Factor.VecVecdouble_end(self)

    def rbegin(self):
        return _Factor.VecVecdouble_rbegin(self)

    def rend(self):
        return _Factor.VecVecdouble_rend(self)

    def clear(self):
        return _Factor.VecVecdouble_clear(self)

    def get_allocator(self):
        return _Factor.VecVecdouble_get_allocator(self)

    def pop_back(self):
        return _Factor.VecVecdouble_pop_back(self)

    def erase(self, *args):
        return _Factor.VecVecdouble_erase(self, *args)

    def __init__(self, *args):
        this = _Factor.new_VecVecdouble(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _Factor.VecVecdouble_push_back(self, x)

    def front(self):
        return _Factor.VecVecdouble_front(self)

    def back(self):
        return _Factor.VecVecdouble_back(self)

    def assign(self, n, x):
        return _Factor.VecVecdouble_assign(self, n, x)

    def resize(self, *args):
        return _Factor.VecVecdouble_resize(self, *args)

    def insert(self, *args):
        return _Factor.VecVecdouble_insert(self, *args)

    def reserve(self, n):
        return _Factor.VecVecdouble_reserve(self, n)

    def capacity(self):
        return _Factor.VecVecdouble_capacity(self)
    __swig_destroy__ = _Factor.delete_VecVecdouble
    __del__ = lambda self: None
VecVecdouble_swigregister = _Factor.VecVecdouble_swigregister
VecVecdouble_swigregister(VecVecdouble)

FACTOR_H = _Factor.FACTOR_H
FACTOR_INVALID = _Factor.FACTOR_INVALID
FACTOR_EDGE_ID = _Factor.FACTOR_EDGE_ID
FACTOR_SPARSEEDGE_ID = _Factor.FACTOR_SPARSEEDGE_ID
FACTOR_GENERAL_ID = _Factor.FACTOR_GENERAL_ID
FACTOR_GENERALSPARSE_ID = _Factor.FACTOR_GENERALSPARSE_ID
class EdgeCreatorStruct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, EdgeCreatorStruct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EdgeCreatorStruct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ei"] = _Factor.EdgeCreatorStruct_ei_set
    __swig_getmethods__["ei"] = _Factor.EdgeCreatorStruct_ei_get
    if _newclass:
        ei = _swig_property(_Factor.EdgeCreatorStruct_ei_get, _Factor.EdgeCreatorStruct_ei_set)
    __swig_setmethods__["ej"] = _Factor.EdgeCreatorStruct_ej_set
    __swig_getmethods__["ej"] = _Factor.EdgeCreatorStruct_ej_get
    if _newclass:
        ej = _swig_property(_Factor.EdgeCreatorStruct_ej_get, _Factor.EdgeCreatorStruct_ej_set)
    __swig_setmethods__["data"] = _Factor.EdgeCreatorStruct_data_set
    __swig_getmethods__["data"] = _Factor.EdgeCreatorStruct_data_get
    if _newclass:
        data = _swig_property(_Factor.EdgeCreatorStruct_data_get, _Factor.EdgeCreatorStruct_data_set)
    __swig_setmethods__["bi"] = _Factor.EdgeCreatorStruct_bi_set
    __swig_getmethods__["bi"] = _Factor.EdgeCreatorStruct_bi_get
    if _newclass:
        bi = _swig_property(_Factor.EdgeCreatorStruct_bi_get, _Factor.EdgeCreatorStruct_bi_set)
    __swig_setmethods__["bj"] = _Factor.EdgeCreatorStruct_bj_set
    __swig_getmethods__["bj"] = _Factor.EdgeCreatorStruct_bj_get
    if _newclass:
        bj = _swig_property(_Factor.EdgeCreatorStruct_bj_get, _Factor.EdgeCreatorStruct_bj_set)
    __swig_setmethods__["NofStates"] = _Factor.EdgeCreatorStruct_NofStates_set
    __swig_getmethods__["NofStates"] = _Factor.EdgeCreatorStruct_NofStates_get
    if _newclass:
        NofStates = _swig_property(_Factor.EdgeCreatorStruct_NofStates_get, _Factor.EdgeCreatorStruct_NofStates_set)

    def __init__(self):
        this = _Factor.new_EdgeCreatorStruct()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Factor.delete_EdgeCreatorStruct
    __del__ = lambda self: None
EdgeCreatorStruct_swigregister = _Factor.EdgeCreatorStruct_swigregister
EdgeCreatorStruct_swigregister(EdgeCreatorStruct)

class SparseEdgeCreatorStruct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SparseEdgeCreatorStruct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SparseEdgeCreatorStruct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["ei"] = _Factor.SparseEdgeCreatorStruct_ei_set
    __swig_getmethods__["ei"] = _Factor.SparseEdgeCreatorStruct_ei_get
    if _newclass:
        ei = _swig_property(_Factor.SparseEdgeCreatorStruct_ei_get, _Factor.SparseEdgeCreatorStruct_ei_set)
    __swig_setmethods__["ej"] = _Factor.SparseEdgeCreatorStruct_ej_set
    __swig_getmethods__["ej"] = _Factor.SparseEdgeCreatorStruct_ej_get
    if _newclass:
        ej = _swig_property(_Factor.SparseEdgeCreatorStruct_ej_get, _Factor.SparseEdgeCreatorStruct_ej_set)
    __swig_setmethods__["data"] = _Factor.SparseEdgeCreatorStruct_data_set
    __swig_getmethods__["data"] = _Factor.SparseEdgeCreatorStruct_data_get
    if _newclass:
        data = _swig_property(_Factor.SparseEdgeCreatorStruct_data_get, _Factor.SparseEdgeCreatorStruct_data_set)
    __swig_setmethods__["mi"] = _Factor.SparseEdgeCreatorStruct_mi_set
    __swig_getmethods__["mi"] = _Factor.SparseEdgeCreatorStruct_mi_get
    if _newclass:
        mi = _swig_property(_Factor.SparseEdgeCreatorStruct_mi_get, _Factor.SparseEdgeCreatorStruct_mi_set)
    __swig_setmethods__["mj"] = _Factor.SparseEdgeCreatorStruct_mj_set
    __swig_getmethods__["mj"] = _Factor.SparseEdgeCreatorStruct_mj_get
    if _newclass:
        mj = _swig_property(_Factor.SparseEdgeCreatorStruct_mj_get, _Factor.SparseEdgeCreatorStruct_mj_set)
    __swig_setmethods__["nnz"] = _Factor.SparseEdgeCreatorStruct_nnz_set
    __swig_getmethods__["nnz"] = _Factor.SparseEdgeCreatorStruct_nnz_get
    if _newclass:
        nnz = _swig_property(_Factor.SparseEdgeCreatorStruct_nnz_get, _Factor.SparseEdgeCreatorStruct_nnz_set)
    __swig_setmethods__["nnzIdx"] = _Factor.SparseEdgeCreatorStruct_nnzIdx_set
    __swig_getmethods__["nnzIdx"] = _Factor.SparseEdgeCreatorStruct_nnzIdx_get
    if _newclass:
        nnzIdx = _swig_property(_Factor.SparseEdgeCreatorStruct_nnzIdx_get, _Factor.SparseEdgeCreatorStruct_nnzIdx_set)
    __swig_setmethods__["bi"] = _Factor.SparseEdgeCreatorStruct_bi_set
    __swig_getmethods__["bi"] = _Factor.SparseEdgeCreatorStruct_bi_get
    if _newclass:
        bi = _swig_property(_Factor.SparseEdgeCreatorStruct_bi_get, _Factor.SparseEdgeCreatorStruct_bi_set)
    __swig_setmethods__["bj"] = _Factor.SparseEdgeCreatorStruct_bj_set
    __swig_getmethods__["bj"] = _Factor.SparseEdgeCreatorStruct_bj_get
    if _newclass:
        bj = _swig_property(_Factor.SparseEdgeCreatorStruct_bj_get, _Factor.SparseEdgeCreatorStruct_bj_set)
    __swig_setmethods__["NofStates"] = _Factor.SparseEdgeCreatorStruct_NofStates_set
    __swig_getmethods__["NofStates"] = _Factor.SparseEdgeCreatorStruct_NofStates_get
    if _newclass:
        NofStates = _swig_property(_Factor.SparseEdgeCreatorStruct_NofStates_get, _Factor.SparseEdgeCreatorStruct_NofStates_set)

    def __init__(self):
        this = _Factor.new_SparseEdgeCreatorStruct()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _Factor.delete_SparseEdgeCreatorStruct
    __del__ = lambda self: None
SparseEdgeCreatorStruct_swigregister = _Factor.SparseEdgeCreatorStruct_swigregister
SparseEdgeCreatorStruct_swigregister(SparseEdgeCreatorStruct)

class CFactorBase(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CFactorBase, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CFactorBase, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    if _newclass:
        RegisterFactorCreator = staticmethod(_Factor.CFactorBase_RegisterFactorCreator)
    else:
        RegisterFactorCreator = _Factor.CFactorBase_RegisterFactorCreator
    if _newclass:
        CreateFactor = staticmethod(_Factor.CFactorBase_CreateFactor)
    else:
        CreateFactor = _Factor.CFactorBase_CreateFactor

    def Primal(self, decode):
        return _Factor.CFactorBase_Primal(self, decode)

    def Dual(self):
        return _Factor.CFactorBase_Dual(self)

    def UpdateMessages(self):
        return _Factor.CFactorBase_UpdateMessages(self)
    __swig_destroy__ = _Factor.delete_CFactorBase
    __del__ = lambda self: None
    FactorID = _Factor.CFactorBase_FactorID
CFactorBase_swigregister = _Factor.CFactorBase_swigregister
CFactorBase_swigregister(CFactorBase)

def CFactorBase_RegisterFactorCreator(ID, creator):
    return _Factor.CFactorBase_RegisterFactorCreator(ID, creator)
CFactorBase_RegisterFactorCreator = _Factor.CFactorBase_RegisterFactorCreator

def CFactorBase_CreateFactor(ID, nodes, data):
    return _Factor.CFactorBase_CreateFactor(ID, nodes, data)
CFactorBase_CreateFactor = _Factor.CFactorBase_CreateFactor

class DenseEdgeFactor(CFactorBase):
    __swig_setmethods__ = {}
    for _s in [CFactorBase]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DenseEdgeFactor, name, value)
    __swig_getmethods__ = {}
    for _s in [CFactorBase]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DenseEdgeFactor, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    FactorID = _Factor.DenseEdgeFactor_FactorID
    __swig_destroy__ = _Factor.delete_DenseEdgeFactor
    __del__ = lambda self: None
DenseEdgeFactor_swigregister = _Factor.DenseEdgeFactor_swigregister
DenseEdgeFactor_swigregister(DenseEdgeFactor)

# This file is compatible with both classic and new-style classes.


